[project]
org = "khronos"
name = "glslang"
source_dir = "{{@@ projects.root_dir @@}}/{{project.org}}/{{project.name}}"
build_dir = "_build/{{user.branch}}"
install_dir = "_build/{{user.branch}}"
build_system = "cmake"
generator = "Ninja Multi-Config"
toolchain = "clang"

[git]
url = "https://github.com/KhronosGroup/glslang.git"
main_branch = "main"
auto_stash = true

[presets.common.definitions]
ENABLE_HLSL = false
BUILD_TESTING = true
ENABLE_OPT = false
INSTALL_GTEST = false

[presets."configs.debug"]
extends = ["common"]

[presets."configs.release"]
extends = ["common"]

# dependences
# python3 update_glslang_sources.py --site github
