[project]
org = "{{@@ projects.source_info['piglit'].org @@}}"
name = "{{@@ projects.source_info['piglit'].name @@}}"
source_dir = "{{@@ projects.root_dir @@}}/{{project.org}}/{{project.name}}"
build_dir = "_build/{{user.branch}}"
install_dir = "_build/{{user.branch}}"
build_system = "cmake"
generator = "Ninja Multi-Config"
toolchain = "clang"

[git]
url = "https://gitlab.freedesktop.org/mesa/piglit.git"
main_branch = "main"
auto_stash = true
