[project]
org = "fd.o"
name = "piglit"
source_dir = "{{env.HOME}}/Projects/{{project.org}}/{{project.name}}"
build_dir = "_build/{{user.branch}}"
install_dir = "_build/{{user.branch}}"
build_system = "cmake"
generator = "Ninja Multi-Config"
toolchain = "clang"

[git]
url = "https://gitlab.freedesktop.org/mesa/piglit.git"
main_branch = "main"
auto_stash = true
