[project]
org = "khronos"
name = "spirv-headers"
source_dir = "{{@@ projects.root_dir @@}}/{{project.org}}/{{project.name}}"

[git]
url = "https://github.com/KhronosGroup/SPIRV-Headers.git"
main_branch = "main"
auto_stash = true
